spring.application.name=Investment-Portfolio_API

spring.datasource.url=jdbc:mysql://localhost/investment_portfolio
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

domain=http://localhost:8080
adding.founds.endpoint=/funds
currency=pln

jwtUtil.expiration = 300000000
jwtUtil.secret=${JWT_UTIL_SECRET}

stripe.secret=${STRIPE_SECRET}

serp.api.secret.key=${SERP_API_SECRET_KEY}

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.admin.chat.id=${TELEGRAM_ADMIN_CHAT_ID}

currency.api.key=${CURRENCY_API_KEY}
